### ISSUE TITLE
Error when running formulas having empty strings

### ISSUE THREAD

**Issue by anitsirc** [mrcsparker/kalc#9]
Hi,

Evaluating a formula crashes if for some reason you happen to have an empty string. 

For example
```ruby
kalc.run('IF(var1=var2,"","ERROR")')
# Or
kalc.run('""')
``` 

Gets the following error message 
```ruby
[8] pry(main)> kalc.run('IF(var1=var2,"","ERROR")')
NoMethodError: private method `eval' called for #<Hash:0x007fd3b38caa80>
from /Users/cristina/.rvm/gems/ruby-2.2.4/gems/kalc-1.1.2/lib/kalc/interpreter.rb:277:in `run'
```

**Comment by mrcsparker** [comment]
Hi @anitsirc 

I just pushed an update to the `blank_strings` branch.  Can you test it out to see if it fixes your issues?

**Comment by anitsirc** [comment]
It works! :) thanks!

**Comment by anitsirc** [comment]
Will you merge this to master, or need to do further testing?

**Comment by mrcsparker** [comment]
I just rebuild and pushed to rubygems: https://rubygems.org/gems/kalc/versions/1.2.0

**Comment by anitsirc** [comment]
Fantastic, thanks!
